### ISSUE TITLE
Media Skin on item pages -- Plyr

### ISSUE THREAD

**Issue by dcnb** [CollectionBuilder/collectionbuilder-sa#14]
https://plyr.io/#video

**Comment by evanwill** [comment]
plyr audio player isn't working smoothly on Chromium on linux-- so... needs some testing

**Comment by evanwill** [comment]
this seems to be an issue with Chrome when using the dev server. I can't play any audio successfully from the dev server, it just starts, plays maybe a second, and seems to get stuck and do nothing. no errors.
