### ISSUE TITLE
Building site locally

### ISSUE THREAD

**Issue by etanus11** [CollectionBuilder/collectionbuilder-sa#5]
Hi,
I downloaded the files to my PC, and wanted to build it again.
There were many problems I had to fix with the dashes. I removed them one by one, but there is one left which I could not solve.(I am not a programmer!).
 here is the output:  I checked the foot.html but could not trace the dash.
Thanks for the help.
Renate
===========
 jekyll s --incremental
Configuration file: /var/www/html/namib_desert/_config.yml
            Source: /var/www/html/namib_desert
       Destination: /var/www/html/namib_desert/_site
 Incremental build: enabled
      Generating... 
  Liquid Exception: Liquid syntax error (line 1): Tag '{%- assign items = site.data[site.metadata] | where_exp: 'item','item.objectid' -%}' was not properly terminated with regexp: /\%\}/ in _includes/foot.html, included in _layouts/default.html
jekyll 3.1.6 | Error:  Liquid syntax error (line 1): Tag '{%- assign items = site.data[site.metadata] | where_exp: 'item','item.objectid' -%}' was not properly terminated with regexp: /\%\}/

 rake deploy --trace
** Invoke deploy (first_time)
** Execute deploy
jekyll build
Configuration file: /var/www/html/namib_desert/_config.yml
            Source: /var/www/html/namib_desert
       Destination: /var/www/html/namib_desert/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 1): Tag '{%- if site.data.theme.featured-image -%}' was not properly terminated with regexp: /\%\}/ in _includes/head/head.html, included in _layouts/default.html
jekyll 3.1.6 | Error:  Liquid syntax error (line 1): Tag '{%- if site.data.theme.featured-image -%}' was not properly terminated with regexp: /\%\}/
rake aborted!
Command failed with status (1): [jekyll build...]
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:67:in `block in create_shell_runner'
/usr/lib/ruby/vendor_ruby/rake/file_utils.rb:57:in `sh'
/var/www/html/namib_desert/Rakefile:10:in `block in <top (required)>'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `block in execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `each'
/usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `execute'
/usr/lib/ruby/vendor_ruby/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/lib/ruby/vendor_ruby/rake/task.rb:193:in `invoke_with_call_chain'
/usr/lib/ruby/vendor_ruby/rake/task.rb:182:in `invoke'
/usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `invoke_task'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `each'
/usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block in top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:125:in `run_with_threads'
/usr/lib/ruby/vendor_ruby/rake/application.rb:110:in `top_level'
/usr/lib/ruby/vendor_ruby/rake/application.rb:83:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:186:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:80:in `run'
/usr/bin/rake:27:in `<main>'
Tasks: TOP => deploy

**Comment by dcnb** [comment]
Hi Renate,

You need to update your jekyll! I didn't notice this before, but it looks
like you're running Jekyll 3.1.6 and Jekyll is currently on 4.1.0 or
something like that. To do this, enter

bundle update

in the command line. That should update all your Ruby gems.

This update will take this problem with the dashes away. It may, of course,
lead to other problems! But hopefully not. At some point, you'll need to
update your Ruby as well, but I think your just at the cutoff right now.
Hopefully this will clear up some of your problems, and I'm sorry I didn't
notice the issue sooner.

-Devin

**Comment by evanwill** [comment]
@etanus11 and @dcnb, I am not sure `bundle update` is going to work in this context. 
So, option 2 if it does *not* update your jekyll version and resolve the issue:

In your terminal try typing the command:

`gem update jekyll bundler`

Then, in the project repository, delete the file named `Gemfile.lock`. Then run `rake deploy` or `jekyll s` and it will automatically generate a new Gemfile.lock using the updated version of jekyll.
