### ISSUE TITLE
error handling in page gen

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/collectionbuilder-sa#6]
@dcnb @owikle check out branch page-gen-errors, 
made a tweak to data_page_generator plugin to give an error message when no data matches the `data` value set in _config,
https://github.com/CollectionBuilder/collectionbuilder-sa/blob/page-gen-errors/_plugins/data_page_generator.rb

if you have the wrong filename set in _config, rather than huge weird ruby error message that doesn't let you know what happened, you get 
"Page Gen Error: Data value '#{data_spec['data']}' does not match any site.data. Please check _config.yml page_gen 'data' value. Common issues are spelling error or including an extension such as .csv (no extension should be used!). Item pages are NOT being generated!"
printed in the terminal. 
HOWEVER, this means that your jekyll s doesn't fail, it just serves up as normal without any page gen happening. 
So rather than it just not working and not having a meaningful error message--with this tweak, it still serves up the site, but mentions that there is a config error. 
which seems nice-- but I am not sure if still serving it up is good?? 

Will people just miss the error message (then be confused by no item pages show up)?? 

Let me know what you think. I think we could definitely build some better error messages in to a few places

**Comment by owikle** [comment]
I think we could make the documentation say something like "Don't see your items? Check the terminal first to see if there's an error message..." just to point people towards where to look. Should there be an error for the `metadata` value too though? I feel like this is the one that people are going to get wrong first, or if page-gen `data` is wrong, `metadata` probably is too.

**Comment by evanwill** [comment]
Having the wrong `metadata` value doesn't throw any breaking error--just nothing will be populated in any of the visualizations.

So wrong `metadata` is a bit harder to detect (can't do it in terminal)--but we could put something into the Liquid on the index page that is like: if site.data.metadata is empty then display a warning, else do the normal thing. So the warning would be in the html page. Could do the same on say subject cloud, check if site.data.metadata is empty, check if the the subjects is empty, if so, replace cloud with alert saying "check your metadata, check your theme config might not being using correct metadata field".
Seems like that might work and be cool. 

However, back on the page-gen error handling, we have had examples so far of people getting the `metadata` value filled in, but don't realize they have to repeat it again for page-gen `data`, then get horrible error code that doesn't let them go any further. So I guess that leans towards printing the error message in terminal, but still letting it not kill jekyll s.
